name: Main

on:
  push:
    branches:
      - main

jobs:
  coverage:
    name: Upload test coverage to codecov.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: "20.14.0"
          cache: pnpm
      - run: pnpm install
      - run: pnpm run coverage
      - uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
